const albums = [
    {
    artist: "2814",
    album: "Birth Of A New Day",
    releaseDate: new Date('2015-01-21'),
    whereToListen: "https://dreamcatalogue.bandcamp.com/album/--18",
    photo: "/assets/images/album-covers/2814-Birth-Of-A-New-Day.jpeg",
    description: "2814 is the collaborative project of original music by the artists HKE and t e l e p a t h. The duo first formed in the early days of Dream Catalogue, dropping the self-titled debut album before going on to find success with their follow-up 'Birth Of A New Day' (or, ‘新しい日の誕生’). 'Birth Of A New Day' was the second album of collaborative duo of HKE and Telepath, working under the name '2814'. A follow up to a relatively minor hit at the time - the self titled debut '2814', 'Birth Of A New Day' ended up becoming a radiant realization of the original project's intention, as both artists expertly mixed and matched ambient palettes and styles to create the vague and distant neon utopia - a sense of romantic melancholy and longing peppered by the suggestive sounds of the world the music inhabited. An album that shaped an era, 'Birth Of A New Day' was quite literal in a prescient manner as it shook the foundations of the underground and catalyzed the 'dreampunk' movement coming out of the post-vaporwave era - helping define the aesthetic of Dream Catalogue as a record label in the process.",
    },
    {
    artist: "ESPRIT 空想",
    album: "200% Electronica",
    releaseDate: new Date('2017-11-17'),
    whereToListen: "https://espritfantasy.bandcamp.com/album/200-electronica",
    photo: "/assets/images/album-covers/Esprit-200-Electronica.jpeg",
    description: "ESPRIT began in 2012 as the sample-based side-project of electronic pop artist 'George Clanton.' ESPRIT's first two EP's 'Girls Only' and 'Summer Night' are still considered essential listening for any newcomers to the vaporwave genre. In 2014, when vaporwave was still defined by its use of found music and manipulated samples, ESPRIT released his 'Virtua.zip' LP composed entirely of original material. In the 3 years since its release, the vaporwave scene at large has followed this trend. After 'Virtua.zip' the ESPRIT series was put on hold while George Clanton's eponymous project's '100% Electronica' LP released in late 2015. Now 3 years later, ESPRIT returns with both the successor to 'Virtua.zip' and the sister album to '100% Electronica' together in one piece. '200% Electronica' combines fully original compositions in ESPRIT's classic vaporwave style with chopped & screwed samples pulled from George Clanton's own songs, inspired by two years of touring with nothing but a Roland SP 404-SX.",
    },
    {
    artist: "CMD 094",
    album: "Aria",
    releaseDate: new Date('2022-07-04'),
    whereToListen: "https://purelifetapes.bandcamp.com/album/aria-ng-3",
    photo: "/assets/images/album-covers/CMD094-Aria.jpeg",
    description: "CMD094 is an ambient producer, mastering engineer, and co-owner of Pure Life Records. With a debut on the newly formed Ukrainian electronic label, Ephemeral Dream, CMD blasted into the Dreampunk scene in the late 2010's. In 2018, he formed a partnership with Panta Rhei to create Pure Life, where CMD would master many of the label's works. The two would also team up to produce as Kuroi Ame. In 2021, upon contracting COVID-19, CMD's cerebral cortex became inflamed, damaging his auditory nerve and hearing.",
    },
    {
    artist: "SOFTWARE",
    album: "Digital-Dance",
    releaseDate: new Date('1988-01-01'),
    whereToListen: "https://software100p.bandcamp.com/album/digital-dance",
    photo: "/assets/images/album-covers/SOFTWARE-Digital-Dance.jpeg",
    description: "The SOFTWARE-Team. Since 1983 do Peter Mergener and Michael Weisser experiment with electronic sounds, visuals and environments. Their special interest is the area of how computers can be used to help express creative art of a wide variety. The LP's and CD's are just one part of Multi-Media-Events, combining music, computer-graphics and high-technology-poetry. SOFTWARE combines these elements beautifully, showing that technology as the sign of the time is emotion, stylish design and a new dimension of high-tech-beauty.",
    },
    {
    artist: "desert sand feels warm at night",
    album: "新 世 界 の 弟 子 た ち",
    releaseDate: new Date('2021-05-21'),
    whereToListen: "https://desertsand.bandcamp.com/album/--25",
    photo: "/assets/images/album-covers/desert-sand-feels-warm-at-night.jpeg",
    description: "desert sand feels warm at night is an experimental vaporwave project of William Hallworth-Cook, best known for both his sample-free and sample-based music in the style of the 'slushwave' subgenre, a style popularized by t e l e p a t h テレパシー能力者. He started making sample-based slushwave in 2018, however he also started releasing sample-free albums in 2019. He is most known for the releases 新 世 界 の 弟 子 た ち and 夢の砂漠.",
    },
    {
    artist: "Macintosh Plus",
    album: "Floral Shoppe",
    releaseDate: new Date('2011-12-09'),
    whereToListen: "https://vektroid.bandcamp.com/album/floral-shoppe",
    photo: "/assets/images/album-covers/Macintosh-Plus-Floral-Shoppe.png",
    description: "Floral Shoppe is the ninth studio album by the American electronic musician Vektroid under the alias Macintosh Plus, released on December 9, 2011 by the independent record label Beer on the Rug. It is her ninth full-length album and was one of the first releases of the 2010s microgenre known as vaporwave to gain popular recognition on the Internet. Since then, Floral Shoppe has been considered by some critics to be the defining album of the style.",
    },
    {
    artist: "猫 シ Corp.",
    album: "Class of '84",
    releaseDate: new Date('2016-04-23'),
    whereToListen: "https://catsystemcorp.bandcamp.com/album/class-of-84",
    photo: "/assets/images/album-covers/Class-Of-84.jpeg",
    description: "Class of '84 is an album by 猫 シ Corp., originally released by Colosseum Records and later given a cassette rerelease by Adhesive Sounds. The Colosseum Records version was removed due to the label purging most of its content, and 猫 シ Corp.'s personal reupload was moved to an individual Bandcamp page due to copyright concerns. In 2021, the album was re-released on cassette and vinyl through Tiger Blood Tapes. The album was later published again on cassette through Cityman Productions in 2022 with updated artwork.",
    },
    {
    artist: "VAPERROR",
    album: "Mana Pool",
    releaseDate: new Date('2014-06-02'),
    whereToListen: "https://vaperror.bandcamp.com/album/mana-pool-2",
    photo: "/assets/images/album-covers/Vaperror-Mana-Pool.jpeg",
    description: "VAPERROR is the experimental vaporwave project of musician Jeff Cardinal, Founder of PLUS100 Records label. VAPERROR is one of the earliest artists to release music under the Vaportrap subgenre, along with incorporating elements from genres such as juke and future bass. Cardinal has experimented in other genres throughout his music career as well, working under different names for these separate projects. He had started producing ambient music under the name Useless, also starting a collaborative ambient project with artist t e l e p a t h テレパシー能力者 called テレヴァペ (roughly translated into televape). He has also produced music as DJ Camgirl, focusing on a more acid house sound. He has worked on another collaborative project called Love Potion with fellow artist COCAINEJESUS.",
    },
    {
    artist: "식료품groceries",
    album: "슈 퍼 마 켓 Yes! We're Open",
    releaseDate: new Date('2014-03-01'),
    whereToListen: "https://groceries-store.bandcamp.com/album/yes-we-re-open",
    photo: "/assets/images/album-covers/Yes-We're-Open-Groceries.jpeg",
    description: "슈퍼마켓Yes! We're Open (Supermarket Yes! We're Open) is the first album by 식료품groceries, published by Dream Catalogue. It was removed from the label following a purge of mostly sample based projects, but was later given a cassette release through the label's DREAMBOX_1 release. In 2018, it received cassette repress through 식료품groceries's personal Bandcamp along with his other two albums. In 2021, the album was published on vinyl through Geometric Lullaby.",
    },
    {
    artist: "Surfing",
    album: "Deep Fantasy",
    releaseDate: new Date('2012-04-03'),
    whereToListen: "https://ssurfing.bandcamp.com/album/deep-fantasy",
    photo: "/assets/images/album-covers/Surfing-Deep-Fantasy.jpeg",
    description: "S U R F I N G, says Leroy, began as a side project while the pair were playing in another band. 'The creative direction [in that band] was just a little bit different than what we wanted to do,' says Leroy. 'Just a matter of taste I guess.' Then, one day Penny sent him an idea he'd worked up in his spare time. 'It was just like, do you want to try to do something with this?' And just like that, S U R F I N G was born…' -Louis Pattison, Bandcamp Daily",
    },
    {
    artist: "ESPRIT 空想",
    album: "virtua.zip",
    releaseDate: new Date('2014-05-07'),
    whereToListen: "https://espritfantasy.bandcamp.com/album/virtua-zip",
    photo: "/assets/images/album-covers/esprit-virtua.jpeg",
    description: "ESPRIT began in 2012 as the sample-based side-project of electronic pop artist 'George Clanton.' ESPRIT's first two EP's 'Girls Only' and 'Summer Night' are still considered essential listening for any newcomers to the vaporwave genre. In 2014, when vaporwave was still defined by its use of found music and manipulated samples, ESPRIT released his 'Virtua.zip' LP composed entirely of original material. In the 3 years since its release, the vaporwave scene at large has followed this trend. After 'Virtua.zip' the ESPRIT series was put on hold while George Clanton's eponymous project's '100% Electronica' LP released in late 2015. Now 3 years later, ESPRIT returns with both the successor to 'Virtua.zip' and the sister album to '100% Electronica' together in one piece. '200% Electronica' combines fully original compositions in ESPRIT's classic vaporwave style with chopped & screwed samples pulled from George Clanton's own songs, inspired by two years of touring with nothing but a Roland SP 404-SX.",
    },
    {
    artist: "SAINT PEPSI",
    album: "Late Night Delight",
    releaseDate: new Date('2013-02-02'),
    whereToListen: "https://mypetflamingo.bandcamp.com/album/late-night-delight",
    photo: "/assets/images/album-covers/Saint-Pepsi-Late-Night-Delight.jpeg",
    description: "LATE NIGHT DELIGHT is a split album between luxury elite and SAINT PEPSI released in 2013. The album is often seen as a pioneer and the inspiration for the 'late night lo-fi' style of vaporwave. The album was published on cassette through Illuminated Paths upon release, and received several represses later on. In 2018, the album was repressed through My Pet Flamingo on vinyl, and later on cassette, CD, and MiniDisc. In 2021, the album was removed from Illuminated Paths following an unauthorized CD release of the album (along with several unauthorized releases of the album in the past), which both artists condemned. In 2022, My Pet Flamingo republished the album again with updated artwork, dubbed as the 'Deluxe' version of the album. The re-release included the previously cassette only bonus tracks, published digitally for the first time.",
    },
    {
    artist: "Eyeliner",
    album: "High Fashion Mood Music",
    releaseDate: new Date('2012-07-12'),
    whereToListen: "https://disasteradio.bandcamp.com/album/high-fashion-mood-music",
    photo: "/assets/images/album-covers/Eyeliner-High-Fashion-Mood-Music.jpeg",
    description: "Eyeliner is a new economical listening experience by Luke Rowell (of Disasteradio prestige). An album tailored to be as acoustically efficient as possible by using the latest in mp3 compression technology! Conceptually following in the grand tradition of muzik library albums whilst paying homage to the legendary output of the late Innovative Communications catalog, High Fashion Mood Music creates 12 seductive environments to relax, unwind and be productive in.",
    },
    {
    artist: "Polygon Dream",
    album: "Zeldawave 2",
    releaseDate: new Date('2020-01-07'),
    whereToListen: "https://marblepawns.bandcamp.com/album/mm",
    photo: "/assets/images/album-covers/Polygon-Dream-Zeldawave2.jpeg",
    description: "Z e l d a w a v e // 近藤 浩治 // OOT (Z e l d a w a v e // Koji Kondo // OOT) is an album released by Marble Pawns under the alias Polygon Dream in 2017, first released as a YouTube video, a SoundCloud set and later as a Bandcamp album. In 2018, it was released through the label Geometric Lullaby, where it got four Cassette publications. In 2021, it was released through Midwest Collective, where it got Cassette, Vinyl, MiniDisc and VHS releases.",
    },
    {
    artist: "Chuck Person",
    album: "Eccojams Vol. 1",
    releaseDate: new Date('2010-08-10'),
    whereToListen: "https://archive.org/details/svhscr_protonmail_03A3",
    photo: "/assets/images/album-covers/Chuck-Person-Eccojams-Vol.1.jpeg",
    description: "Chuck Person's Eccojams Vol. 1 is an album by American electronic musician Daniel Lopatin under the pseudonym Chuck Person. An album of plunderphonic chopped and screwed remixes, Eccojams Vol. 1 features songs that consist of looped samples from popular songs from the 1980s and 1990s, with effects such as reverb and pitch shifting being applied. The results tend to highlight mournful or existential lyrics from its sampled sources. Prior to Eccojams Vol. 1's release, Lopatin posted a series of videos he called 'eccojams' to a YouTube channel named 'sunsetcorp'. The album was released under the label The Curatorial Club on August 8, 2010, with a run of 100 cassette tapes. An official remastered version was released for digital download in November 2016. Though obscure, it was used as a template for the genre of vaporwave and is thus widely considered to be influential to said genre. By the 2016 remaster's release, recognition for Eccojams Vol. 1 had grown, with the original tapes being sold off of Discogs for hundreds of dollars.",
    },
    {
    artist: "INTERNET CLUB",
    album: "Redefining The Workplace",
    releaseDate: new Date('2012-04-21'),
    whereToListen: "https://internetclub.bandcamp.com/album/redefining-the-workplace",
    photo: "/assets/images/album-covers/Internet-Club-Redefining-The-Workplace.jpeg",
    description: "INTERNET CLUB is the vaporwave project of producer Robin Burnett, half of Datavision Ltd. and co-founder of Hexagon Recordings. It is one of the earliest vaporwave projects, with releases dating back as early as 2011. The project contributed much to the early vaporwave scene in both sampling technique and theming. The artist is also responsible for the term 'vaporwave' being used as a genre descriptor for a previously loose group of early producers. Before a hiatus beginning in 2013, a majority of INTERNET CLUB's albums were released exclusively on file hosts. An unofficial archival Bandcamp page was created on November 15, 2014 by YouTube user AAAAAAAAAA42. This Bandcamp has been maintained by Robin since 2015, with the first official release through the page being SOUND CANVAS.",
    },
    {
    artist: "Luxury Elite",
    album: "World Class",
    releaseDate: new Date('2015-07-21'),
    whereToListen: "https://crashsymbols.bandcamp.com/album/world-class",
    photo: "/assets/images/album-covers/luxury-elite-world-class.jpeg",
    description: "luxury elite is an anonymous vaporwave artist and founder of the fortune 500 and Prevue Guide labels and Neon Nights radio show, based in Kentucky, United States. She is credited as an early founder of the 'late night lo-fi' style of vaporwave music, as well as the inventor of the term. In 2016, after the release of Trifusion with Tendencies the artist underwent an extended hiatus that was broken almost two years later with the release of prism, followed by another two year hiatus broken with the release of high society.",
    },
    {
    artist: "nmesh",
    album: "Dream Sequins",
    releaseDate: new Date('2014-02-27'),
    whereToListen: "https://nmesh.bandcamp.com/album/dream-sequins",
    photo: "/assets/images/album-covers/nmesh-dream-sequins.jpeg",
    description: "Nmesh is an electronic music project of a Kentucky-based artist Alex Koenig. Notably, Koenig is known for his music discography going back to the late 1990's, starting as a drummer in metal band Execrate in middle school. The Nmesh project has a discography spanning back to 2001 in IDM-experimental genres, but in 2013 the artist began experimenting within the vaporwave genre with Nu.wav Hallucinations. From that point on, Koenig has successfully created works inside and outside of the scene.",
    },
    {
    artist: "Macross 82-99",
    album: "Sailorwave",
    releaseDate: new Date('2017-08-17'),
    whereToListen: "https://neoncityrecords.bandcamp.com/album/sailorwave",
    photo: "/assets/images/album-covers/Macross82-99-Sailorwave.jpeg",
    description: "Macross 82-99 is a Mexican electronic music producer and DJ from Mexico City, based out of Osaka, Japan. His music combines elements of plunderphonics, disco, jazz fusion, house, hip hop and city pop, and commonly makes use of video games, Japanese pop culture, as well as 80s and 90s anime, most notably Sailor Moon, as aesthetic tropes. Macross 82-99's 2013 albums ネオ東京 (English: Neo Tokyo) and SAILORWAVE, along with musical cohort Saint Pepsi's Hit Vibes, are commonly cited as the origin point for the 'future funk' subgenre of vaporwave, which combines the sample-based production approach and visual language of vaporwave with French house and dance music influences.",
    },
    {
    artist: "Eco Virtual",
    album: "Atmospheres 第1",
    releaseDate: new Date('2013-01-01'),
    whereToListen: "https://ecovirtual.bandcamp.com/album/atmospheres-1",
    photo: "/assets/images/album-covers/Eco-Virtual-Atmospheres.jpeg",
    description: "Eco Virtual is an anonymous vaporwave artist based in Canada, best known for their ATMOSPHERES series of albums. Eco Virtual's releases primarily revolve around an educational, weather-technology-based aesthetic, as self-branded 'Atmospheric Research & Analysis Music'. The identity of Eco Virtual is mostly kept vague, though a close association to the 'Hologram Bay' project has led some to believe it is a sister project of Blank Banshee, if not simply the result of a close friendship. With the release of ATMOSPHERES 第4, the artist has undergone an extended hiatus, though in 2017 a brief period of activity including tweets and a Facebook livestream occurred.",
    },
    {
    artist: "Windows96",
    album: "Plume Valley",
    releaseDate: new Date('2017-08-03'),
    whereToListen: "https://windows96.bandcamp.com/album/plume-valley",
    photo: "/assets/images/album-covers/windows96.jpeg",
    description: "Windows 96 is an electronic music project by Brazilian composer and producer Gabriel Eduardo. Combining the sound of synth/vaporwave, psychedelic, VGM and more."
    },
    {
    artist: "Telepath テレパシー能力者/Vaperror",
    album: "テレヴァペ",
    releaseDate: new Date('2016-10-03'),
    whereToListen: "https://plus100.bandcamp.com/album/-",
    photo: "/assets/images/album-covers/televape.jpeg",
    description: "テレヴァペ is the combined efforts of electronic music producers VAPERROR and t e l e p a t h テレパシー能力者. They present to you 超越愛, a unique interpretation of ambient funk, jazz, and synth music driven by love.",
    },
    {
    artist: "Haircuts For Men",
    album: "nothing special, nothing wonderful",
    releaseDate: new Date('2020-02-17'),
    whereToListen: "https://haircutsformen.bandcamp.com/album/nothing-special-nothing-wonderful",
    photo: "/assets/images/album-covers/haircuts-for-men.jpeg",
    description: "The fundamentals—screeching saxes and looping, apathetic, and beat-driven funk riffs—are executed in great style here. Dreamy synth tones waver subtly below the surface of tracks, deepening their texture. Samples are selected and deployed well. The album keeps a bitter-sweet edge, rather than suffusing to sardonic, insufferable cynicism. Beats are littered with just enough frills, fills and flourishes to maintain interest for the duration of nothing special…. nothing special, nothing wonderful attempts to nullify its own existence with that title. There's nothing particularly groundbreaking or unfamiliar on the album. But if that's what you came to vaporwave for, maybe you're missing the point. As haircuts for men says, “everything is plundered.” But, as plundering goes, this is more of a casino heist than a drunken scrump.",
    },
    {
    artist: "猫 シ Corp.",
    album: "Palm Mall",
    releaseDate: new Date('2014-10-02'),
    whereToListen: "https://catsystemcorp.bandcamp.com/album/palm-mall",
    photo: "/assets/images/album-covers/palm.jpeg",
    description: "Palm Mall is the sixth studio album by Cat System Corp., the alias of Dutch electronic musician Jornt Elzinga. Released on 2 October 2014, its nine tracks use sample of elevator music to explore shopping malls. Following the success of Hiraeth (2014), Elzinga drew inspiration from the 'vaporwave vibe' he felt in the video game Grand Theft Auto V (2013), and produced Palm Mall as his first 'serious try' at a mallsoft release. It was a turning point for Elzinga's music and is his favorite release of the Cat System Corp. discography, featuring participation of several other vaporwave musicians.",
    },
]

// Export the seed data to `models/index.js`
module.exports = albums
